### ISSUE TITLE
Missing transfers_comments :compile_as_copy_if_needed in YETriple

### ISSUE THREAD

**Issue by dmajda** [yast/y2r#48]
The `transfers_comments` declaration in the `YETriple` class is missing `:compile_as_copy_if_needed` as an argument.

This omission can cause lost comments. For example, if the `packager` YaST module is retranslated, the `key_manager_dialogs.rb` file is missing a comment above the following lines:

``` ruby
expires == 0 ?
  _("The key never expires.") :
  # %1 is the date when the GPG key expires (e.g. '21.3.2015') or "Never"
```

**Comment by cwh42** [comment]
In case that this problem has not already been fixed in the past we don't need to fix it now either.
