### ISSUE TITLE
Carriage Return (CR, "\r") is translated to Space (" ")

### ISSUE THREAD

**Issue by mvidner** [yast/y2r#49]
See the openSUSE bug https://bugzilla.novell.com/show_bug.cgi?id=853725 where the symptom is that a proxy test always seems to fail.

Trivial test, `cr.ycp`

``` cpp
{ return "\r"; }
```

results in `cr.rb`

``` ruby
...
    def main
      " "
    end
...
```

**Comment by cwh42** [comment]
In case that this problem has not already been fixed in the past we don't need to fix it now either.
